name: public-experience-api

networks:
  default:
    name: services
volumes:
  redis_data:

services:
  redis:
    image: redis/redis-stack:latest
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./deployments/docker/redis/redis.conf:/opt/redis-stack/etc/redis.conf
      - redis_data:/data

  workers:
    build:
      context: .
      dockerfile: deployments/docker/workers/Dockerfile
    networks:
      - default
    depends_on:
      redis:
        condition: service_healthy

  public:
    build:
      context: .
      dockerfile: deployments/docker/public/Dockerfile
    networks:
      - default
    depends_on:
      redis:
        condition: service_healthy
      workers:
        condition: service_started
    ports:
      - "${PUBLIC_PORT:-8080}:8080"

  docs:
    build:
      context: .
      dockerfile: deployments/docker/docs/Dockerfile
    ports:
      - "${DOCS_PORT:-8081}:8080"
    environment:
      API_REFERENCE_CONFIG: |
        {
          "url": "/docs/swagger.json",
          "baseServerURL": "${REFERENCE_CONFIG_PUBLIC_HOST}"
        }
    depends_on:
      public:
        condition: service_started
