version: '3'

dotenv: ['.env']

tasks:
  build:docs:
    cmds:
      - swag fmt
      - swag init --parseDependency -dir ./services/api/endpoints --output ./internal/docs

  build:api: go build -ldflags "-w -s" -o bin/public-api.exe services/api/cmd/main.go
  build:tasks: go build -ldflags "-w -s" -o bin/tasks.exe services/tasks/cmd/main.go

  dev:api:
    cmd: air --build.cmd "task build:docs && task build:api" --build.bin "bin\\public-api.exe" --build.exclude_dir "internal\\db,internal\\docs"
    env:
      ENVIRONMENT: development
  dev:tasks:
    cmd: air --build.cmd "task build:tasks" --build.bin "bin\\tasks.exe"
    env:
      ENVIRONMENT: development