// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/oaklands/changelogs": {
            "get": {
                "description": "Fetch a list of changelog versions with their information.",
                "tags": [
                    "Oaklands"
                ],
                "parameters": [
                    {
                        "enum": [
                            "desc",
                            "asc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "The direction to order by. This will use the changelog's date to order.",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/v1/oaklands/changelogs/{version}": {
            "get": {
                "description": "Fetch a changelog version.",
                "tags": [
                    "Oaklands"
                ],
                "responses": {}
            }
        },
        "/v1/oaklands/economy/stock-market/ores": {
            "get": {
                "description": "Fetch the current ore stock market.",
                "tags": [
                    "Oaklands"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ETag to validate cached response.",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "name",
                            "current_multiplier",
                            "last_multiplier",
                            "values.current_value",
                            "values.base_value"
                        ],
                        "type": "string",
                        "default": "current_multiplier",
                        "description": "The field to sort by.",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "desc",
                            "asc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "The direction to order by.",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Oaklands.V1.StockMarket"
                                    }
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/oaklands/economy/stock-market/rocks": {
            "get": {
                "description": "Fetch the current rock stock market.",
                "tags": [
                    "Oaklands"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ETag to validate cached response.",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "name",
                            "current_multiplier",
                            "last_multiplier",
                            "values.current_value",
                            "values.base_value"
                        ],
                        "type": "string",
                        "default": "current_multiplier",
                        "description": "The field to sort by.",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "desc",
                            "asc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "The direction to order by.",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Oaklands.V1.StockMarket"
                                    }
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/oaklands/economy/stock-market/trees": {
            "get": {
                "description": "Fetch the current tree stock market.",
                "tags": [
                    "Oaklands"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ETag to validate cached response.",
                        "name": "If-None-Match",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "name",
                            "current_multiplier",
                            "last_multiplier",
                            "values.current_value",
                            "values.base_value"
                        ],
                        "type": "string",
                        "default": "current_multiplier",
                        "description": "The field to sort by.",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "desc",
                            "asc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "The direction to order by.",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Oaklands.V1.StockMarket"
                                    }
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/oaklands/sync": {
            "get": {
                "description": "Fetch information on when data was last synced from the game.\nIt should be noted that a majority of data is fetched when checking if the experience was updated,\nsuch as newsletters and changelogs. Some content with resync at certain intervals by itself\nalongside update sync checks.\u003cbr\u003e\u003cbr\u003e\nInternally, updates are checked for every **5 minutes**.",
                "tags": [
                    "Oaklands"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/Oaklands.V1.Sync"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/API.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "API.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "The message for the returned error.",
                    "type": "string"
                },
                "type": {
                    "description": "The type of error that was returned.",
                    "type": "string"
                }
            }
        },
        "Oaklands.V1.MaterialValues": {
            "type": "object",
            "properties": {
                "base_value": {
                    "description": "The base value for the material.",
                    "type": "number"
                },
                "current_value": {
                    "description": "The current value of the material.",
                    "type": "number"
                },
                "type": {
                    "description": "The type of material.",
                    "type": "string"
                }
            }
        },
        "Oaklands.V1.StockMarket": {
            "type": "object",
            "properties": {
                "currency_type": {
                    "description": "The currency of the material.",
                    "type": "string"
                },
                "current_multiplier": {
                    "description": "The current multiplier.",
                    "type": "number"
                },
                "display_name": {
                    "description": "The display name of the material.",
                    "type": "string"
                },
                "last_multiplier": {
                    "description": "The multipler from the last time the stock refreshed.",
                    "type": "number"
                },
                "name": {
                    "description": "The identifier for the material.",
                    "type": "string"
                },
                "values": {
                    "description": "The values of the different types for the materials",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Oaklands.V1.MaterialValues"
                    }
                }
            }
        },
        "Oaklands.V1.Sync": {
            "type": "object",
            "properties": {
                "meta": {
                    "description": "Information from the experience that is used for sync checks.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Oaklands.V1.SyncMeta"
                        }
                    ]
                },
                "stock_market": {
                    "description": "Sync information for the stock market.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Oaklands.V1.SyncdInfoWithReset"
                        }
                    ]
                }
            }
        },
        "Oaklands.V1.SyncMeta": {
            "type": "object",
            "properties": {
                "last_update": {
                    "description": "The last time that data from Oaklands that can be updated from experience changes was synced and updated.",
                    "type": "string"
                },
                "next_check": {
                    "description": "The next time Oaklands will be checked for an update.",
                    "type": "string"
                }
            }
        },
        "Oaklands.V1.SyncdInfoWithReset": {
            "type": "object",
            "properties": {
                "last_sync": {
                    "description": "The last time that the resource was updated.",
                    "type": "string"
                },
                "next_sync": {
                    "description": "The next time that the resource will be updated",
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "All of the available Oaklands endpoints.",
            "name": "Oaklands"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Typical Developers - Public Experience API",
	Description:      "This is the official, publicly accessible, API to get data in Typical Developers' experiences.\n# Notes\n- All dates and timestamps are returned in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format and are set as a UTC timezone.<br>\n---\n# Caching\nAll responses will return an `ETag` header, which is an MD5 hash of the response. You are able to use this hash to verify\nif there's updated content by supplying a `If-None-Match` in the requests header for the next request you make.<br>\n- Status `200 - OK` will be returned if the resource has been updated.\n- Status `304 - Not Modified` will be returned if the resource has not been updated.\n---\n# Ratelimits\nAt the moment, the API does not have any rate limits. Please use the API responsibly by following good practices.\nAbuse detection will result in a indefinite ban from accessing the API. Please reach out in our [Discord Server](https.discord.gg/typical)\nif you have ran into this issue.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
