definitions:
  API.ErrorResponse:
    properties:
      message:
        description: The message for the returned error.
        type: string
      type:
        description: The type of error that was returned.
        type: string
    type: object
  Oaklands.V1.MaterialValues:
    properties:
      base_value:
        description: The base value for the material.
        type: number
      current_value:
        description: The current value of the material.
        type: number
      type:
        description: The type of material.
        type: string
    type: object
  Oaklands.V1.StockMarket:
    properties:
      currency_type:
        description: The currency of the material.
        type: string
      current_multiplier:
        description: The current multiplier.
        type: number
      display_name:
        description: The display name of the material.
        type: string
      last_multiplier:
        description: The multipler from the last time the stock refreshed.
        type: number
      name:
        description: The identifier for the material.
        type: string
      values:
        description: The values of the different types for the materials
        items:
          $ref: '#/definitions/Oaklands.V1.MaterialValues'
        type: array
    type: object
  Oaklands.V1.Sync:
    properties:
      last_content_sync:
        description: The last time that data from Oaklands that can be updated from
          experience changes was synced.
        type: string
      stock_market:
        allOf:
        - $ref: '#/definitions/Oaklands.V1.UpdatedInfoWithReset'
        description: Sync information for the stock market.
    type: object
  Oaklands.V1.UpdatedInfoWithReset:
    properties:
      last_sync:
        description: The last time that the resource was updated.
        type: string
      next_sync:
        description: The next time that the resource will be updated
        type: string
    type: object
info:
  contact: {}
  description: |-
    This is the official, publicly accessible, API to get data in Typical Developers' experiences.
    # Notes
    - All dates and timestamps are returned in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format and are set as a UTC timezone.<br>
    ---
    # Caching
    All responses will return an `ETag` header, which is an MD5 hash of the response. You are able to use this hash to verify
    if there's updated content by supplying a `If-None-Match` in the requests header for the next request you make.<br>
    - Status `200 - OK` will be returned if the resource has been updated.
    - Status `304 - Not Modified` will be returned if the resource has not been updated.
    ---
    # Ratelimits
    At the moment, the API does not have any rate limits. Please use the API responsibly by following good practices.
    Abuse detection will result in a indefinite ban from accessing the API. Please reach out in our [Discord Server](https.discord.gg/typical)
    if you have ran into this issue.
  title: Typical Developers - Public Experience API
paths:
  /v1/oaklands/economy/stock-market/ores:
    get:
      description: Fetch the current ore stock market.
      parameters:
      - description: ETag to validate cached response.
        in: header
        name: If-None-Match
        type: string
      - default: current_multiplier
        description: The field to sort by.
        enum:
        - name
        - current_multiplier
        - last_multiplier
        - values.current_value
        - values.base_value
        in: query
        name: sort_by
        type: string
      - default: desc
        description: The direction to order by.
        enum:
        - desc
        - asc
        in: query
        name: order_by
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/Oaklands.V1.StockMarket'
                type: array
            type: object
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/API.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/API.ErrorResponse'
      tags:
      - Oaklands
  /v1/oaklands/economy/stock-market/rocks:
    get:
      description: Fetch the current rock stock market.
      parameters:
      - description: ETag to validate cached response.
        in: header
        name: If-None-Match
        type: string
      - default: current_multiplier
        description: The field to sort by.
        enum:
        - name
        - current_multiplier
        - last_multiplier
        - values.current_value
        - values.base_value
        in: query
        name: sort_by
        type: string
      - default: desc
        description: The direction to order by.
        enum:
        - desc
        - asc
        in: query
        name: order_by
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/Oaklands.V1.StockMarket'
                type: array
            type: object
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/API.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/API.ErrorResponse'
      tags:
      - Oaklands
  /v1/oaklands/economy/stock-market/trees:
    get:
      description: Fetch the current tree stock market.
      parameters:
      - description: ETag to validate cached response.
        in: header
        name: If-None-Match
        type: string
      - default: current_multiplier
        description: The field to sort by.
        enum:
        - name
        - current_multiplier
        - last_multiplier
        - values.current_value
        - values.base_value
        in: query
        name: sort_by
        type: string
      - default: desc
        description: The direction to order by.
        enum:
        - desc
        - asc
        in: query
        name: order_by
        type: string
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                items:
                  $ref: '#/definitions/Oaklands.V1.StockMarket'
                type: array
            type: object
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/API.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/API.ErrorResponse'
      tags:
      - Oaklands
  /v1/oaklands/sync:
    get:
      description: |-
        Fetch information on when data was last synced from the game.<br>
        It should ne noted that a majority of data is refetched from Oaklands every 5 minutes.
      responses:
        "200":
          description: OK
          schema:
            properties:
              data:
                $ref: '#/definitions/Oaklands.V1.Sync'
            type: object
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/API.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/API.ErrorResponse'
      tags:
      - Oaklands
swagger: "2.0"
tags:
- description: All of the available Oaklands endpoints.
  name: Oaklands
